### ISSUE TITLE
Example deploy fails

### ISSUE THREAD

**Issue by JoseCarlosPPK** [pklaus/docker-cassandra-pv-archiver#1]
If I do 
```sh
docker compose up
```
in the directory *example-deployment*, the *cassandra-pv-archiver* fails and it exited with code 1:

cassandra-pv-archiver-1  | 2024-07-15 17:22:37.415  INFO 13 --- [           main] c.a.c.p.s.s.ArchiveServerApplication     : Starting Cassandra PV Archiver v3.2.6 with PID 13
cassandra-pv-archiver-1  | 2024-07-15 17:22:38.365 ERROR 13 --- [           main] o.s.boot.SpringApplication               : Application startup failed
cassandra-pv-archiver-1  | 
cassandra-pv-archiver-1  | java.lang.IllegalStateException: Cannot load configuration class: com.aquenos.cassandra.pvarchiver.server.spring.ArchiveServerApplication
cassandra-pv-archiver-1  | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:403) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:249) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:281) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at com.aquenos.cassandra.pvarchiver.server.spring.ArchiveServerApplication.main(ArchiveServerApplication.java:515) ~[com.aquenos.cassandra.pvarchiver.cassandra-pv-archiver-server-3.2.6.jar:3.2.6]
cassandra-pv-archiver-1  | Caused by: java.lang.ExceptionInInitializerError: null
cassandra-pv-archiver-1  | 	at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:122) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:110) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:393) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	... 9 common frames omitted
cassandra-pv-archiver-1  | Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @270fcfcc
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:174) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:153) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	... 12 common frames omitted
cassandra-pv-archiver-1  | Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @270fcfcc
cassandra-pv-archiver-1  | 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[na:na]
cassandra-pv-archiver-1  | 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
cassandra-pv-archiver-1  | 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[na:na]
cassandra-pv-archiver-1  | 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193) ~[na:na]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554) ~[na:na]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) ~[org.springframework.spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	... 24 common frames omitted
cassandra-pv-archiver-1  | 
cassandra-pv-archiver-1  | 2024-07-15 17:22:38.384  WARN 13 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception thrown from LifecycleProcessor on context close
cassandra-pv-archiver-1  | 
cassandra-pv-archiver-1  | java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@57cf54e1: startup date [Mon Jul 15 17:22:37 UTC 2024]; root of context hierarchy
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:417) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1002) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:794) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at com.aquenos.cassandra.pvarchiver.server.spring.ArchiveServerApplication.main(ArchiveServerApplication.java:515) ~[com.aquenos.cassandra.pvarchiver.cassandra-pv-archiver-server-3.2.6.jar:3.2.6]
cassandra-pv-archiver-1  | 
cassandra-pv-archiver-1  | 2024-07-15 17:22:38.385 ERROR 13 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception
cassandra-pv-archiver-1  | 
cassandra-pv-archiver-1  | java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@57cf54e1: startup date [Mon Jul 15 17:22:37 UTC 2024]; root of context hierarchy
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[org.springframework.spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) ~[org.springframework.spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) ~[org.springframework.spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961) ~[org.springframework.spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) ~[org.springframework.spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968) ~[org.springframework.spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961) ~[org.springframework.spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:794) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[org.springframework.boot.spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
cassandra-pv-archiver-1  | 	at com.aquenos.cassandra.pvarchiver.server.spring.ArchiveServerApplication.main(ArchiveServerApplication.java:515) ~[com.aquenos.cassandra.pvarchiver.cassandra-pv-archiver-server-3.2.6.jar:3.2.6]
cassandra-pv-archiver-1  |
cassandra-pv-archiver-1 exited with code 1

**Comment by JoseCarlosPPK** [comment]
Im using Docker version 27.0.3, build 7d4bcd8 on Ubuntu 22.04.4 LTS, if it helps
